# Generated by Django 5.1.4 on 2026-06-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.CharField(help_text='ID unik ahli (mis. dari Kobo _uuid).', max_length=64, unique=True)),
                ('nama', models.CharField(blank=True, max_length=200)),
                ('instansi', models.CharField(blank=True, max_length=200)),
                ('tipologi', models.CharField(choices=[('akademisi', 'Akademisi/Peneliti'), ('pemerintah', 'Pemerintah/OPD'), ('praktisi', 'Praktisi/Penyuluh'), ('masyarakat', 'Tokoh Masyarakat/Petani')], max_length=20)),
                ('kobo_submission_id', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True, help_text='False jika ada matriks tidak konsisten (CR>0.10).')),
                ('catatan_validasi', models.JSONField(blank=True, default=dict, help_text='Hasil cek CR per blok.')),
            ],
            options={
                'ordering': ['tipologi', 'expert_id'],
            },
        ),
        migrations.CreateModel(
            name='PairwiseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('konstruk', 'Antar Konstruk (5x5)'), ('k1', 'Indikator Kesesuaian Lahan (3x3)'), ('k2', 'Indikator Daya Dukung Lingkungan (3x3)'), ('k3', 'Indikator Risiko Iklim & Bencana (3x3)'), ('k4', 'Indikator Nilai Konservasi (3x3)'), ('k5', 'Indikator Faktor Sosial-Ekonomi (4x4)')], max_length=20)),
                ('i', models.PositiveSmallIntegerField(help_text='Indeks elemen-i (0-based).')),
                ('j', models.PositiveSmallIntegerField(help_text='Indeks elemen-j (0-based, j>i).')),
                ('value', models.FloatField(help_text='Nilai bertanda ±1..±9 (skala Saaty).')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_values', to='kobo_mce.expertresponse')),
            ],
            options={
                'ordering': ['block', 'i', 'j'],
                'unique_together': {('response', 'block', 'i', 'j')},
            },
        ),
    ]
